### ISSUE TITLE
Add a compile option to concatenate each breakpoint into a separate file

### ISSUE THREAD

**Issue by rupl** [Snugug/respond-to#3]
The workflow Respond-to provides is totally awesome. Period.

However, the output scatters media queries throughout the compiled CSS. Oftentimes it is still desirable to group styles of a certain media query in a separate file. Common use cases would be situations where conditional loading is desired (via Modernizr.load or eCSSential to name two examples).

Would it be possible to provide a compile option that does this? It would make Respond-to a silver bullet in terms of simplifying CSS workflow while providing drop-in integration with major front-end performance tools.

**Comment by Snugug** [comment]
God I wish I could Chris, I wish I could.  

Currently, Sass is unable to group like media queries together and while I'm investigating hackie solutions to do this, having it then spit out separate files becomes another altogether that I don't know is possible to do through a mixin.

Rest assured, I'm looking into figuring out a way of doing this and similar things, but as of right now it may not be possible without changes to Sass core  

~ Sam Richard
http://snug.ug

**Comment by Snugug** [comment]
For more information on this, see [Issue 241](https://github.com/nex3/sass/issues/241)

**Comment by rupl** [comment]
Thanks for the link, I will follow the upstream issue!

**Comment by Snugug** [comment]
Closing this thanks to upstream. Will update when upstream gets pushed
