### ISSUE TITLE
Support $no-query functionality from Breakpoint

### ISSUE THREAD

**Issue by rupl** [Snugug/respond-to#8]
Respond-to doesn't support `$no-query` fallbacks and having this feature would be super cool.

**Comment by Snugug** [comment]
Fixed

**Comment by barraponto** [comment]
Docs?

**Comment by Snugug** [comment]
See Breakpoint. Same syntax and usage

**Comment by rupl** [comment]
For those following at home, docs can be found here: https://github.com/canarymason/breakpoint#no-query-fallback
